export const mockIncidents = [
    { id: "INC-1001", title: "Server Down", status: "Open", priority: "High", description: "Main server is unresponsive." },
    { id: "INC-1002", title: "Database Error", status: "In Progress", priority: "Medium", description: "DB connection timeout." },
    { id: "INC-1003", title: "API Failure", status: "Resolved", priority: "Low", description: "External API not responding." },
    { id: "INC-1004", title: "Login Issue", status: "Open", priority: "High", description: "Users unable to login." },
    { id: "INC-1005", title: "Memory Leak", status: "Investigating", priority: "Critical", description: "High memory usage detected." },
    { id: "INC-1006", title: "Disk Failure", status: "In Progress", priority: "High", description: "Disk IO errors observed." },
    { id: "INC-1007", title: "Network Latency", status: "Resolved", priority: "Medium", description: "Slow network response times." },
    { id: "INC-1008", title: "Security Breach", status: "Critical", priority: "High", description: "Unauthorized access detected." },
    { id: "INC-1009", title: "App Crash", status: "Open", priority: "High", description: "Application crashes on launch." },
    { id: "INC-1010", title: "Backup Failure", status: "Investigating", priority: "Medium", description: "Scheduled backup not completed." },
    { id: "INC-1011", title: "Load Balancer Failure", status: "Open", priority: "High", description: "Traffic not evenly distributed." },
    { id: "INC-1012", title: "Cloud Service Outage", status: "In Progress", priority: "Critical", description: "AWS/GCP/Azure outage detected." },
    { id: "INC-1013", title: "Email Delivery Issue", status: "Resolved", priority: "Low", description: "Emails not being sent to users." },
    { id: "INC-1014", title: "Unauthorized Data Access", status: "Critical", priority: "High", description: "Sensitive user data accessed illegally." },
    { id: "INC-1015", title: "Software Patch Failure", status: "Investigating", priority: "Medium", description: "Latest software update failed." },
    { id: "INC-1016", title: "Storage Overload", status: "Open", priority: "High", description: "System running out of storage space." },
    { id: "INC-1017", title: "Mobile App Crash", status: "In Progress", priority: "Medium", description: "iOS and Android app crashing on login." },
    { id: "INC-1018", title: "Firewall Misconfiguration", status: "Resolved", priority: "Low", description: "Traffic blocked due to incorrect firewall rules." },
    { id: "INC-1019", title: "Slow Response Time", status: "Investigating", priority: "Medium", description: "High latency on API endpoints." },
    { id: "INC-1020", title: "DDoS Attack", status: "Critical", priority: "High", description: "High traffic detected from malicious sources." },
    { id: "INC-1021", title: "VPN Connectivity Issue", status: "Open", priority: "Medium", description: "Users unable to connect via VPN." },
    { id: "INC-1022", title: "Payment Processing Delay", status: "In Progress", priority: "High", description: "Transactions taking longer than expected." },
    { id: "INC-1023", title: "Service Degradation", status: "Investigating", priority: "Medium", description: "Performance issues reported." },
    { id: "INC-1024", title: "Hardware Failure", status: "Open", priority: "Critical", description: "Physical hardware component failure detected." },
    { id: "INC-1025", title: "Multi-Factor Authentication Failure", status: "In Progress", priority: "High", description: "MFA not sending verification codes." },
    { id: "INC-1026", title: "Container Crash", status: "Investigating", priority: "Medium", description: "Docker container stops unexpectedly." },
    { id: "INC-1027", title: "High CPU Usage", status: "Resolved", priority: "Low", description: "CPU utilization above threshold." },
    { id: "INC-1028", title: "Cloud Function Timeout", status: "Open", priority: "Medium", description: "Cloud function execution taking too long." },
    { id: "INC-1029", title: "IoT Device Malfunction", status: "In Progress", priority: "High", description: "Connected IoT devices not responding." },
    { id: "INC-1030", title: "Data Synchronization Issue", status: "Investigating", priority: "Medium", description: "Real-time sync failing between databases." }
];
